openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8018'
    description: Generated server url
paths:
  '/budget':
    post:
      tags:
        - budgget-controller
      operationId: dummyFunction
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DriscollResponseString'
components:
  schemas:
    DriscollResponseString:
      type: object
      properties:
        status:
          type: integer
          format: int32
        data:
          type: string
